services:
  injectived0:
    container_name: devnet-validator-0
    image: "${DOCKER_IMAGE}"
    environment:
      - DEBUG=0
      - NODE_HOME=/root/.injectived
      - CHAIN_ID=injective-1
      - MONIKER=validator-0
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "10337:10337"
      - "9900:9900"
      - "9091:9091"
      - "6060:2345"
      - "8545-8546:8545-8546"
      - "26660:26660"
    volumes:
      - ./validators/0:/root/.injectived:Z
    networks:
      localnet:
        ipv4_address: 172.127.0.2
    command: injectived --home=/root/.injectived start
  injectived1:
    container_name: devnet-validator-1
    image: "${DOCKER_IMAGE}"
    environment:
      - DEBUG=0
      - NODE_HOME=/root/.injectived
      - CHAIN_ID=injective-1
      - MONIKER=validator-1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./validators/1:/root/.injectived:Z
    networks:
      localnet:
        ipv4_address: 172.127.0.3
    command: injectived --home=/root/.injectived start
  injectived2:
    container_name: devnet-validator-2
    image: "${DOCKER_IMAGE}"
    environment:
      - DEBUG=0
      - NODE_HOME=/root/.injectived
      - CHAIN_ID=injective-1
      - MONIKER=validator-2
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./validators/2:/root/.injectived:Z
    networks:
      localnet:
        ipv4_address: 172.127.0.4
    command: injectived --home=/root/.injectived start
  injectived3:
    container_name: devnet-validator-3
    image: "${DOCKER_IMAGE}"
    environment:
      - DEBUG=0
      - NODE_HOME=/root/.injectived
      - CHAIN_ID=injective-1
      - MONIKER=validator-3
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./validators/3:/root/.injectived:Z
    networks:
      localnet:
        ipv4_address: 172.127.0.5
    command: injectived --home=/root/.injectived start

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/24
